# Generated by Django 5.0.2 on 2025-09-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='trip',
        ),
        migrations.DeleteModel(
            name='RouteSegment',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
